n = input()
n = n.replace("c=", "1")
n = n.replace("c-", "1")
n = n.replace("dz=", "1")
n = n.replace("d-", "1")
n = n.replace("lj", "1")
n = n.replace("nj", "1")
n = n.replace("s=", "1")
n = n.replace("z=", "1")

print(len(n))